-- Limpia vistas anteriores de ActivityTimeline que ya no alimentan el reporte de horas.
-- El reporte nuevo usa RPT_AT_EVENTOS_DETALLE_HORAS,
-- RPT_AT_HORAS_PERSONA_TIPO_PERIODO y RPT_AT_HORAS_EQUIPO_TIPO_PERIODO.

DROP VIEW IF EXISTS RPT_CAPACIDAD_SEMANA;
DROP VIEW IF EXISTS FACT_CAPACIDAD;
DROP VIEW IF EXISTS RPT_AT_HORAS_PERSONA_TIPO;
DROP VIEW IF EXISTS RPT_AT_HORAS_USADAS_EVENTO;
